all: UCR_DTW.cpp UCR_DTW_BIN.cpp UCR_ED.cpp UCR_ED_BIN.cpp
	g++ -O3 UCR_DTW.cpp -o UCR_DTW
	g++ -O3 UCR_DTW_BIN.cpp -o UCR_DTW_BIN
	g++ -O3 UCR_ED.cpp -o UCR_ED
	g++ -O3 UCR_ED_BIN.cpp -o UCR_ED_BIN

clean:
	rm -f UCR_DTW
	rm -f UCR_DTW_BIN
	rm -f UCR_ED
	rm -f UCR_ED_BIN
	
